# Site settings
title: flipdot-gmd
description: >
  A jekyll site to test github-md-editor with. This is not our main website, for
  that go to https://flipdot.org/!

nav_items:
  - text: Blog
    href: /
  - text: Projekte
    href: /projekte
  - text: Kontakt
    href: /kontakt

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap

permalink: pretty

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

excerpt_separator: <!-- more -->

markdown: kramdown
sass:
  style: compressed

exclude:
  - vendor/
  - Gemfile
  - Gemfile.lock
  - README.md
